local option = vim.opt

option.autoindent = true
option.smartindent = true
option.cursorline = true
option.scrolloff = 8
option.clipboard = "unnamedplus"
option.undofile = true
option.signcolumn = "yes"
option.showmode = false
option.mouse = ""
option.hlsearch = true
option.tabstop = 4
option.number = true
option.relativenumber = true
option.shiftwidth = 4
option.splitbelow = true
option.splitright = true
option.inccommand = "split"
option.timeoutlen = vim.g.vscode and 1000 or 300 -- Lower than default (1000) to quickly trigger which-key
